language: python
arch:
  - amd64
  - ppc64le
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
dist: xenial
addons:
  apt:
    packages:
      - libsodium18
      - graphviz
      - bind9

before_install:
  - sudo chown -Rvf $USER:$GROUP ~/.cache/pip/wheels
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - python tests/offline_tests.py
  - python tests/local_probe_tests.py
